name: Main Workflow
on:
  push:
    branches:
      - [main]

jobs:
  deploy-main:
    runs-on: [self-hosted, main-server]
    steps:
      - name: Update Main
        run: |
          cd /workspace
          git checkout main
          git pull origin main
          echo "Main server updated from remote!"
  update-staging:
    runs-on: [self-hosted, staging-server]
    steps:
      - name: Update Staging
        run: |
          cd /workspace
          git checkout main
          git pull origin main
          git checkout staging
          git reset --hard main
          git push origin staging --force
          echo "Staging remote updated!"
          git checkout main
          echo "Now in main!"
