name: Main Workflow
on:
  push:
    branches:
      - [main]

jobs:
  deploy-main:
    runs-on: [self-hosted, main-server]
    steps:
      - name: Update Main
        run: |
          set x
          cd /Users/lesterreandino/Desktop/testproj/act-github-actions/act-github-actions
          git checkout main
          git pull origin main
          git checkout staging
          git reset --hard main
          git pull origin staging
          echo "Main Updated!"
