name: Staging Workflow
on:
  push:
    branches:
      - [staging]

jobs:
  deploy-staging:
    runs-on: [self-hosted, staging-server]
    steps:
      - name: Update Staging
        run: |
          set x
          cd /workspace
          git checkout main
          git pull origin main
          git checkout staging
          git reset --hard main
          git pull origin staging
          echo "Staging Updated!"
