name: Test Workflow
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: [self-hosted, staging-server]
    steps:
      - name: Update Staging
        run: |
          echo "Hello Test"
