name: Test Workflow
on:
  push:
    branches:
      - [main]

jobs:
  deploy:
    # runs-on: [self-hosted, staging-server]
    runs-on: ubuntu-latest
    steps:
      - name: Update Staging
        run: |
          set x
          cd /Users/lesterreandino/Desktop/testproj/act-github-actions/act-github-actions
          git status
          echo "Hello Test"
